name: Jekyll site CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the site
      run: |
        echo "chmod 777 . Gemfile.lock"
        docker run -v "${{ github.workspace }}:/srv/jekyll" -u "$(id -u)" jekyll/jekyll:3 \
          /bin/bash -c "jekyll build"
    - name: Check the hyperlinks via html-proofer
      run: |
        docker run -v ${{ github.workspace }}:/srv/jekyll jekyll/jekyll:3 \
          /bin/bash -c "rake"
    - name: Upload the result (_site)
      uses: actions/upload-artifact@v2
      with:
        name: site
        path: _site/
